variables:
  GOOGLE_APPLICATION_CREDENTIALS: /secret/keyfile.json
  CONTAINER_REGISTRY: gcr.io/palpantlab-main/oauth2_proxy

stages:
  - test
  - build

# For master builds, push the commit and update the :latest tag.
build_master-x84-64:
  stage: build
  tags:
    - k8s
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor build --dockerfile=$CI_PROJECT_DIR/Dockerfile --destination=$CONTAINER_REGISTRY:latest --destination=$CONTAINER_REGISTRY:$CI_COMMIT_SHA --context $CI_PROJECT_DIR
  only:
    - master

build_master-arm64:
  stage: build
  tags:
    - k8s
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor build --dockerfile=$CI_PROJECT_DIR/Dockerfile.arm64 --destination=$CONTAINER_REGISTRY:latest-arm64 --destination=$CONTAINER_REGISTRY:$CI_COMMIT_SHA-arm64 --context $CI_PROJECT_DIR
  only:
    - master
    
test-go-1-12:
  stage: test
  tags:
    - k8s
  image:
    name: golang:1.12-stretch
    entrypoint: [""]
  script:
    - wget -O dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
    - chmod +x dep
    - mv dep $GOPATH/bin/dep
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.17.1
    - ./configure
    - make test
    
